### ISSUE TITLE
Exception when trying to insert a list (0.6.0)

### ISSUE THREAD

**Issue by adamdougal** [scassandra/scassandra-java-client#39]
I'm having an issue priming a prepared statement which is an insert of a list type.

Code:
```
PrimingRequest primeRequestInsert = PrimingRequest.preparedStatementBuilder()
                .withQuery("INSERT INTO test_table (a_column) VALUES (?)")
                .withVariableTypes(ListType.list(PrimitiveType.TEXT))
                .withResult(PrimingRequest.Result.success)
                .build();

primingClient.prime(primeRequestInsert);

PreparedStatement preparedStatement = session.prepare("INSERT INTO test_table (a_column) VALUES (?)");
BoundStatement boundStatement = preparedStatement.bind(Arrays.asList("a value"));
session.execute(boundStatement);
```
Produces this error:
```
Uncaught error from thread [CassandraServerStub-1900-1901-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[CassandraServerStub-1900-1901]
java.lang.NoSuchMethodError: org.apache.cassandra.serializers.ListSerializer.deserializeForNativeProtocol(Ljava/nio/ByteBuffer;I)Ljava/util/List;
	at org.scassandra.server.cqlmessages.types.CqlList.readValue(CqlList.scala:39)
	at org.scassandra.server.cqlmessages.request.ExecuteRequest$$anonfun$1.apply(ExecuteRequest.scala:49)
	at org.scassandra.server.cqlmessages.request.ExecuteRequest$$anonfun$1.apply(ExecuteRequest.scala:48)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.scassandra.server.cqlmessages.request.ExecuteRequest$.versionTwoWithTypes(ExecuteRequest.scala:48)
	at org.scassandra.server.cqlmessages.VersionTwoMessageFactory$.parseExecuteRequestWithVariables(VersionTwoMessageFactory.scala:47)
	at org.scassandra.server.actors.PrepareHandler$$anonfun$receive$1.applyOrElse(PrepareHandler.scala:55)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$Akk[ERROR] [03/18/2015 20:14:09.478] [CassandraServerStub-1900-1901-akka.actor.default-dispatcher-3] [ActorSystem(CassandraServerStub-1900-1901)] Uncaught error from thread [CassandraServerStub-1900-1901-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: org.apache.cassandra.serializers.ListSerializer.deserializeForNativeProtocol(Ljava/nio/ByteBuffer;I)Ljava/util/List;
	at org.scassandra.server.cqlmessages.types.CqlList.readValue(CqlList.scala:39)
	at org.scassandra.server.cqlmessages.request.ExecuteRequest$$anonfun$1.apply(ExecuteRequest.scala:49)
	at org.scassandra.server.cqlmessages.request.ExecuteRequest$$anonfun$1.apply(ExecuteRequest.scala:48)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.scassandra.server.cqlmessages.request.ExecuteRequest$.versionTwoWithTypes(ExecuteRequest.scala:48)
	at org.scassandra.server.cqlmessages.VersionTwoMessageFactory$.parseExecuteRequestWithVariables(VersionTwoMessageFactory.scala:47)
	at org.scassandra.server.actors.PrepareHandler$$anonfun$receive$1.applyOrElse(PrepareHandler.scala:55)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
	at akka.actor.ActorCell.invoke(ActorCell.scala:456)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkaForkJoinTask.exec(AbstractDispatcher.scala:385)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
kaForkJoinTask.exec(AbstractDispatcher.scala:385)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by adamdougal** [comment]
Turns out I was brining in this dependency:

org.apache.cassandra:cassandra-clientutil:2.0.8

Removing/upgrading this fixed the issue.
Doh!
